apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ml-pipeline
  name: ml-pipeline-config
data:
  config.json: |
    {
      "DBConfig": {
        "Host": "$(mysqlHost)",
        "Port": "3306",
        "DriverName": "mysql",
        "DataSourceName": "",
        "DBName": "$(pipelineMysqlDb)",
        "GroupConcatMaxLen": "4194304"
      },
      "ObjectStoreConfig": {
        "Host": "s3.amazonaws.com",
        "Region": "$(awsRegion)",
        "Secure": true,
        "BucketName": "$(pipelineBucket)",
        "PipelineFolder": "$(pipelinePath)",
        "PipelinePath": "$(pipelinePath)"
      },
      "InitConnectionTimeout": "6m",
      "DefaultPipelineRunnerServiceAccount": "pipeline-runner"
    }