apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# Replace with your namespace
namespace: kubeflow

# add your IAM annotations here
commonAnnotations:
  # kube2iam annotations
  iam.amazonaws.com/role: kube2iam-role
  # eks iam annotations
  # eks.amazonaws.com/role-arn: eks-role

patchesStrategicMerge:
  - viewer-tensorboard-template-configmap.yaml

configMapGenerator:
  - name: pipeline-aws-parameters
    behavior: merge
    env: params.env

generatorOptions:
  disableNameSuffixHash: true


vars:
  - name: awsIAMAnnotationKey
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.awsIAMAnnotationKey
  - name: awsIAMRole
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.awsIAMRole

configurations:
  - params.yaml
